apiVersion: v1
kind: Secret
metadata:
  name: pocketbase-secret
  namespace: mustard
  labels:
    app: "pocketbase"
stringData:
  PB_SUPERUSER_EMAIL: <email>
  PB_SUPERUSER_PASSWORD: <password>
---
apiVersion: "baas.pb.simplified/v1"
kind: "Pocketbase"
metadata:
  name: "pocketbase"
  namespace: mustard
  labels:
    app: "pocketbase"
spec:
  name: test
  image: simplifiedreg.azurecr.io/simplifactu/pocketbase:0.1.0-2025020514
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  secretRef:
    name: "pocketbase-secret"
  volumes:
    storageClassName: "local-path"
    accessModes: 
      - "ReadWriteOnce"
    storageSize: "1Gi"
    volumeMountPath: "/data"
  ingress:
    ingressClassName: "traefik" 
    hosts:
    - host: baas.simplified.com
      paths:
      - path: "/"
        pathType: "Prefix"
    # tls:
    # - secretName: "pocketbase-tls"
    #   hosts:
    #   - "baas.test.com"
