apiVersion: "baas.pb.simplified/v1"
kind: "Pocketbase"
metadata:
  name: "pocketbase"
  namespace: mustard
  labels:
    app: "pocketbase"
spec:
  name: test
  image: adrianmusante/pocketbase:0.24.4
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  volumes:
    storageClassName: "local-path"
    accessModes: 
      - "ReadWriteOnce"
    storageSize: "1Gi"
    volumeMountPath: "/data"
  ingress:
    ingressClassName: "kong" 
    hosts:
    - host: baas.test.com
      paths:
      - path: "/"
        pathType: "Prefix"
    # tls:
    # - secretName: "pocketbase-tls"
    #   hosts:
    #   - "baas.test.com"